config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :dashboard, only: [:index] do
    collection do
      get :get_cors
      post :post_cors
    end
  end

  resources :shop, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout false, :except => :index
  skip_before_filter :verify_authenticity_token, :only => [:post_cors]
  before_filter :set_cors_headers, :except => :index

  def index
  end

  def get_cors
  end

  def post_cors
    @params = post_params
  end


  private

  def post_params
    params.require(:customer).permit(:id, :first_name, :last_name)
  end

  def set_cors_headers
    response.headers['Access-Control-Allow-Origin'] = 'http://test-shop.com:3000'
    response.headers['Access-Control-Allow-Methods'] = 'GET, POST, PUT, OPTIONS'
    response.headers['Access-Control-Allow-Credentials'] = true
    response.headers['Content-Type'] = 'text/html; charset=utf-8'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/dashboard/get_cors.html.erb
<span>GET CORS Content</span>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<%= render 'shared/menu' %>

app/views/dashboard/post_cors.html.erb
<span>POST CORS Content</span>
<br/>
<span>POST params:</span><%= @params.inspect %>

app/views/home/index.html.erb
<h1>Home</h1>
<%= render 'shared/menu' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AliveTest</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <%= javascript_include_tag 'cors' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_menu.html.erb
<ul>
  <li><%= link_to 'Home', root_url(host: 'test-main.com')%></li>
  <li><%= link_to 'Dashboard', dashboard_index_url(host: 'test-main.com')%></li>
  <li><%= link_to 'Shop', shop_index_url(host: 'test-shop.com')%></li>
</ul>

app/views/shop/index.html.erb
<script type="text/javascript">
  jQuery( document ).ready(function() {

    // Handle GET request
    jQuery('a.cors-request-get-link').click(function(e){
      event.preventDefault();
      var url = jQuery(this).data('url');

      //This will not work!
      // $.ajax({
      //   url: 'http://test-main.com:3000/dashboard/get_cors',
      //   success: function(result){
      //     $('div.cors-respond-container').html(result);
      //   }
      // });

      // This actually works
      jQuery.ajax({
        type: 'GET',
        url: url,
        contentType: 'text/plain',
        xhrFields: {
          withCredentials: true
        },
        headers: {
        },
        success: function(data) {
          jQuery('div.cors-respond-container').html(data);
        },
        error: function() {
        }
      });
    });


    // Handle POST request
    jQuery('a.cors-request-post-link').click(function(e){
      event.preventDefault();
      var url = jQuery(this).data('url');
      jQuery.ajax({
        type: 'POST',
        url: url,
        data:{
          customer: {
            id: "100",
            first_name: "John",
            last_name: "Doe",
          },
        },
        contentType: 'application/x-www-form-urlencoded',
        xhrFields: {
          withCredentials: true
        },
        headers: {
        },
        success: function(data) {
          jQuery('div.cors-respond-container').html(data);
        },
        error: function() {
        }
      });
    });

  });
</script>

<h1>Shop</h1>
<%= render 'shared/menu' %>


<h3>CORS AJAX Requests:</h3>
<ul>
  <li><a href="#" class="cors-request-get-link", data-url="<%= get_cors_dashboard_index_url(host: 'test-main.com') %>">Make GET CORS request to Dashboard</a></li>
  <li><a href="#" class="cors-request-post-link", data-url="<%= post_cors_dashboard_index_url(host: 'test-main.com') %>">Make POST CORS request to Dashboard</a></li>
</ul>

<br/>
<span>CORS respond:</span>
<br/>
<div class="cors-respond-container"></div>